AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  AZ:
    Description: Availability Zone
    Type: String
    Default: "cn-north-1"

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      AvailabilityZone: !Ref AZ
      ImageId: ami-032d6db78f84e8bf5
      SecurityGroups:
        - !Ref MySecurityGroup

  # add elastic ip to instance
  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyEC2Instance
