# kubectl exec -ti pod-secrets-via-env -- env
apiVersion: v1
kind: Pod
metadata:
  name: pod-secrets-via-env
spec:
  containers:
  - name: mycontainer
    image: redis
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: super-secret
            key: credential
  restartPolicy: Never