apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: nginx
    volumeMounts:
    - name: cache-volume
      mountPath: /usr/share/nginx/html
    livenessProbe:
      exec:
        command:
        - cat
        - /usr/share/nginx/html
      initialDelaySeconds: 5
      periodSeconds: 5      
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', 'touch /workdir/calm.txt']
    volumeMounts:
    - mountPath: /workdir
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}